### ISSUE TITLE
icon themes

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/gtk3-feedstock#2]
Should we create packages for `hicolor-icon-theme` and `adwaita-icon-theme` and add them as dependencies to `gtk3`?

While using a package with a gtk UI, I ran into this error:

```
(ipython:40519): Gtk-WARNING **: 23:00:59.274: Error loading theme icon 'system-run' for stock: Icon 'system-run' not present in theme Adwaita
```

According to [this thread][1], that error can be fixed by installing `adwaita-icon-theme` (formerly `gnome-icon-theme`).

[1]: https://github.com/Homebrew/legacy-homebrew/issues/34337

Related links:

- https://github.com/conda-forge/staged-recipes/issues/3918
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/hicolor-icon-theme.rb
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/adwaita-icon-theme.rb

**Comment by ryanvolz** [comment]
Yeah, looks like something we should do! They both look like autotools builds that will be straightforward on Linux/OSX at least. I'm surprised this wasn't needed earlier for any gtk2 apps.

**Comment by ryanvolz** [comment]
I'm 90% of the way to working recipes for both. One snag is that `adwaita-icon-theme` uses `gtk3` to build the icon index cache, so having `gtk3` depend on `adwaita-icon-theme` would be tricky. Maybe it could work because it's only a build dependency, or maybe we can rework it so that `adwaita-icon-theme` is build cache-less but the cache gets included in the `gtk3` package. Something to ponder.

**Comment by ryanvolz** [comment]
I'm leaning toward the latter solution: build `adwaita-icon-theme` without `gtk3`, add it as a dependency to `gtk3`, and run `gtk-update-icon-cache $PREFIX/share/icons/Adwaita` at the end of the `gtk3` build script to create the cache file. This looks like it will work in my local testing.

**Comment by ryanvolz** [comment]
Recipe pull request: https://github.com/conda-forge/staged-recipes/pull/11147

**Comment by ryanvolz** [comment]
> I'm leaning toward the latter solution: build `adwaita-icon-theme` without `gtk3`, add it as a dependency to `gtk3`, and run `gtk-update-icon-cache $PREFIX/share/icons/Adwaita` at the end of the `gtk3` build script to create the cache file. This looks like it will work in my local testing.

So this works, but it builds a very stripped-down version of `adwaita-icon-theme` that doesn't have png fallback versions for the svg icons. I'm not sure if these are strictly necessary, but we probably want them. What this means is that we need to find a way to break the cyclic dependency that would arise from having `adwaita-icon-theme` depend on `gtk3` and vice-versa.

Linux packagers split `gtk3` up into many subpackages, but copying that to its fullest extent seems excessive for us. The fundamental problem is that we want a `gtk3` to build other packages against, and for that we don't care about installing `adwaita-icon-theme`, but for end-use at runtime people are going to expect icons if they install and use `gtk3`. So what we need are at least two package outputs from the `gtk3` source:

- one that has the library and things needed for building `adwaita-icon-theme` and other packages that depend on `gtk3`, and
- one that depends on the first and also adds a dependency for `adwaita-icon-theme`.

Where to draw the line between those and what to call them is where I could use some input.

### Proposal 1
3 packages that mimic what e.g. Debian does:

- `gtk-update-icon-cache`: contains that binary and depends only on `gdk-pixbuf` (This binary is needed by `adwaita-icon-theme` and other hypothetical packages that would add icons add build time, and it might also be helpful as a runtime dependency?)
- `gdk3` or `libgdk3`: contains the `libgdk` library and a few extras that only depend on `libgdk`, namely `gtk-encode-symbolic-svg` (This binary is needed by `adwaita-icon-theme` to generate pngs from svgs, but only at build time)
- `gtk3`: contains everything else and depends on the first two, and it also depends on `adwaita-icon-theme` so that users can be guaranteed some icons

I like this because packages that just want `gtk3` can build against and depend on the `gtk3` package and things will just work for them. The potential downside is that it's not immediately obvious from the names why the first two packages should exist or what people might use them for. It's also a little bit more work to set up and maintain.

### Proposal 2
Keep it as simple as possible with 1 real package and 1 metapackage:

- `libgtk3` or just `gtk3` is exactly what the current `gtk3` package is, meaning that it doesn't depend on `adwaita-icon-theme` in any way
- `gtk3` or `gtk3-runtime` (or something!) is a metapackage that depends on the first and `adwaita-icon-theme`

The appeal of this scheme is that it's very simple to implement, with no wondering which package contains which files. The downside is that these two packages should have names that obviously communicate their purpose, and I don't think I've achieved that. Other packages would probably want to build against the real package but have a runtime dependency for the metapackage, and while this could probably be done with `run_exports`, I'm not aware of any other `conda` packages that split things up in this way. Do such examples exist?

Feedback on these options or other ideas would be most welcome before I set off on implementing something. `adwaita-icon-theme` is also held up a bit by needing `librsvg` on Windows, so at least I have that to look into in the meantime.

**Comment by ryanvolz** [comment]
I've thought of a much simpler solution: just add `adwaita-icon-theme` to `run_exports`. That way applications that build against `gtk3` will get a run dependency on `adwaita-icon-theme` and they will get icons as expected. I'm not sure if there is a use case where another package would just have a run dependency on `gtk3` and expect icons, but if there is then we can address it when it's needed with a metapackage (e.g. create a `gtk3_runtime` which depends on `gtk3` and `adwaita-icon-theme` and tell those packages to depend on `gtk3_runtime`).

**Comment by stuarteberg** [comment]
Thanks for handling this, Ryan!  Sorry I was no help.

**Comment by ryanvolz** [comment]
I was motivated by my downstream application of interest not having icons on Windows, so no worries!
